main:
  - name: 主页
    url: '/'
    weight: 10
  - name: DIY策略
    url: '/course'
    weight: 20
    identifier: courses
  - name: 中国
    url: '/course/china/'
    weight: 10
    parent: courses
  - name: 全球
    url: '/course/global/'
    weight: 20
    parent: courses
  - name: 饕客说
    url: '/post'
    weight: 30
  - name: 欢迎交流
    url: '/contact'
    weight: 60
  