main:
  - name: 主页
    url: '/'
    weight: 10
  - name: 课程
    url: '/course'
    weight: 20
    identifier: courses
  - name: 数据科学
    url: '/course/example/'
    weight: 10
    parent: courses
  - name: 博客
    url: '/post'
    weight: 30
  - name: 联系
    url: '/contact'
    weight: 60
  